[build]
  publish   = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"

[functions."server"]
  included_files = ["views/**", "data/**"]

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server/:splat"
  status = 200
